baseURL = "http://example.org/"
languageCode = "en-us"
title = "First Site"
theme = "ga-hugo-theme"
[taxonomies]
  tag = "tags"
  categorie = "categories"
  mood = "moods"

[context.production.environment]
  HUGO_VERSION = "0.30.2"
